// https://i.ibb.co/6cBP4fYK/2022-Audi-A6.png
// https://i.ibb.co/fsHcc9J/bmw330i.png
// https://i.ibb.co/N6z6TBvn/bmwi8coupe.png
// https://i.ibb.co/8DHkLPcK/bmwX5m.png
// https://i.ibb.co/XfYwYjxs/cadillac-escalade.png
// https://i.ibb.co/67TK0YWw/Chevrolet-Malibu.png
// https://i.ibb.co/679zxRDN/ford-f150.png
// https://i.ibb.co/3mhxZrdw/ford-mustang-Gt.png
// https://i.ibb.co/MyhXHfyp/Ford-Explorer.png
// https://i.ibb.co/q462rxD/honda-civic.png
// https://i.ibb.co/C5YCZXC5/huyndai-elantra.png
// https://i.ibb.co/tycr1Ly/hyundai-tucson.png
// https://i.ibb.co/60Z8Bmht/kia-k5-2022.png
// https://i.ibb.co/chLxwh11/mazda-cx-5.png
// https://i.ibb.co/KpxmFtDq/nissan-rogue-2022.png
// https://i.ibb.co/VY03q4rX/subar-legacy.png
// https://i.ibb.co/39g1hCV7/tesla-model3.png
// https://i.ibb.co/Z1xqz2hF/toyota-camry.png
// https://i.ibb.co/pBDmDvhT/toyota-corolla.png
// https://i.ibb.co/kVVjtPRV/toyota-prius-2022.png
// https://i.ibb.co/nNkKDC8W/volkswagen-atlas.png
// https://i.ibb.co/jPBRk1gk/volkswagen-golf.png
// https://i.ibb.co/KpdQ4pqy/volkswagen-jetta.png
// https://i.ibb.co/PzT9963y/volvo-xc60.png
// https://i.ibb.co/Cs1HbyJp/volvo-v40.png

export const cars = [
  {
    city_mpg: 30,
    class: "compact car",
    combination_mpg: 34,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 38,
    make: "Toyota",
    model: "Corolla",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/pBDmDvhT/toyota-corolla.png"
  },
  {
    city_mpg: 27,
    class: "midsize car",
    combination_mpg: 30,
    cylinders: 4,
    displacement: 2.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 35,
    make: "Toyota",
    model: "Camry",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/Z1xqz2hF/toyota-camry.png"
  },
  {
    city_mpg: 26,
    class: "midsize car",
    combination_mpg: 29,
    cylinders: 4,
    displacement: 2.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 34,
    make: "Subaru",
    model: "Legacy",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/VY03q4rX/subar-legacy.png"
  },
  {
    city_mpg: 55,
    class: "compact car",
    combination_mpg: 52,
    cylinders: 0,
    displacement: null,
    drive: "fwd",
    fuel_type: "electricity",
    highway_mpg: 54,
    make: "Tesla",
    model: "Model 3",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/39g1hCV7/tesla-model3.png"
  },
  {
    city_mpg: 18,
    class: "suv",
    combination_mpg: 20,
    cylinders: 6,
    displacement: 3.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 23,
    make: "Ford",
    model: "Explorer",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/MyhXHfyp/Ford-Explorer.png"
  },
  {
    city_mpg: 24,
    class: "compact car",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 34,
    make: "Honda",
    model: "Civic",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/q462rxD/honda-civic.png"
  },
  {
    city_mpg: 22,
    class: "midsize car",
    combination_mpg: 25,
    cylinders: 6,
    displacement: 3.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "BMW",
    model: "330i",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/fsHcc9J/bmw330i.png"
  },
  {
    city_mpg: 20,
    class: "pickup truck",
    combination_mpg: 22,
    cylinders: 6,
    displacement: 3.5,
    drive: "4wd",
    fuel_type: "gas",
    highway_mpg: 25,
    make: "Ford",
    model: "F-150",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/679zxRDN/ford-f150.png"
  },
  {
    city_mpg: 22,
    class: "suv",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Mazda",
    model: "CX-5",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/chLxwh11/mazda-cx-5.png"
  },
  {
    city_mpg: 28,
    class: "compact car",
    combination_mpg: 32,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 37,
    make: "Hyundai",
    model: "Elantra",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/C5YCZXC5/huyndai-elantra.png"
  },
  {
    city_mpg: 19,
    class: "luxury sedan",
    combination_mpg: 22,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 27,
    make: "Audi",
    model: "A6",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/6cBP4fYK/2022-Audi-A6.png"
  },
  {
    city_mpg: 21,
    class: "suv",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Volvo",
    model: "XC60",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/PzT9963y/volvo-xc60.png"
  },
  {
    city_mpg: 23,
    class: "sedan",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 31,
    make: "Kia",
    model: "K5",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/60Z8Bmht/kia-k5-2022.png"
  },
  {
    city_mpg: 49,
    class: "compact car",
    combination_mpg: 52,
    cylinders: 0,
    displacement: null,
    drive: "fwd",
    fuel_type: "hybrid",
    highway_mpg: 53,
    make: "Toyota",
    model: "Prius",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/kVVjtPRV/toyota-prius-2022.png"
  },
  {
    city_mpg: 23,
    class: "compact car",
    combination_mpg: 27,
    cylinders: 4,
    displacement: 1.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 33,
    make: "Chevrolet",
    model: "Malibu",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/67TK0YWw/Chevrolet-Malibu.png"
  },
  {
    city_mpg: 16,
    class: "luxury suv",
    combination_mpg: 18,
    cylinders: 8,
    displacement: 4.4,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 21,
    make: "BMW",
    model: "X5 M",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/8DHkLPcK/bmwX5m.png"
  },
  {
    city_mpg: 17,
    class: "sports car",
    combination_mpg: 19,
    cylinders: 8,
    displacement: 5.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 24,
    make: "Ford",
    model: "Mustang GT",
    transmission: "m",
    year: 2022,
    image: "https://i.ibb.co/3mhxZrdw/ford-mustang-Gt.png"
  },
  {
    city_mpg: 22,
    class: "suv",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.4,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Hyundai",
    model: "Tucson",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/tycr1Ly/hyundai-tucson.png"
  },
  {
    city_mpg: 15,
    class: "luxury suv",
    combination_mpg: 17,
    cylinders: 8,
    displacement: 6.2,
    drive: "4wd",
    fuel_type: "gas",
    highway_mpg: 20,
    make: "Cadillac",
    model: "Escalade",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/XfYwYjxs/cadillac-escalade.png"
  },
  {
    city_mpg: 24,
    class: "crossover",
    combination_mpg: 27,
    cylinders: 4,
    displacement: 2.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 31,
    make: "Nissan",
    model: "Rogue",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/KpxmFtDq/nissan-rogue-2022.png"
  },
  {
    city_mpg: 27,
    class: "coupe",
    combination_mpg: 29,
    cylinders: 3,
    displacement: 1.5,
    drive: "awd",
    fuel_type: "hybrid",
    highway_mpg: 32,
    make: "BMW",
    model: "i8",
    transmission: "a",
    year: 2020,
    image: "https://i.ibb.co/N6z6TBvn/bmwi8coupe.png"
  },
  {
    city_mpg: 30,
    class: "hatchback",
    combination_mpg: 32,
    cylinders: 4,
    displacement: 1.4,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "Volkswagen",
    model: "Golf",
    transmission: "a",
    year: 2019,
    image: "https://i.ibb.co/jPBRk1gk/volkswagen-golf.png"
  },
  {
    city_mpg: 29,
    class: "sedan",
    combination_mpg: 31,
    cylinders: 4,
    displacement: 1.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "Volkswagen",
    model: "Jetta",
    transmission: "a",
    year: 2021,
    image: "https://i.ibb.co/KpdQ4pqy/volkswagen-jetta.png"
  },
  {
    city_mpg: 24,
    class: "suv",
    combination_mpg: 27,
    cylinders: 6,
    displacement: 3.6,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "Volkswagen",
    model: "Atlas",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/nNkKDC8W/volkswagen-atlas.png"
  },
  {
    city_mpg: 24,
    class: "hatchback",
    combination_mpg: 27,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 34,
    make: "Volvo",
    model: "V40",
    transmission: "a",
    year: 2019,
    image: "https://i.ibb.co/Cs1HbyJp/volvo-v40.png"
  },
  {
    city_mpg: 13,
    class: "coupe",
    combination_mpg: 15,
    cylinders: 12,
    displacement: 6.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 18,
    make: "Lamborghini",
    model: "Aventador",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/Mx7Cdm5R/Lamborghini-Aventador.png"
  },
  {
    city_mpg: 14,
    class: "coupe",
    combination_mpg: 16,
    cylinders: 10,
    displacement: 5.2,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 19,
    make: "Lamborghini",
    model: "Huracan",
    transmission: "a",
    year: 2023,
    image: "https://i.ibb.co/n8kWwVNV/Lamborghini-huracan.png"
  },
  {
    city_mpg: 12,
    class: "convertible",
    combination_mpg: 14,
    cylinders: 12,
    displacement: 6.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 17,
    make: "Lamborghini",
    model: "Revuelto",
    transmission: "a",
    year: 2024,
    image: "https://i.ibb.co/HfR6sCNB/Lamborghini-revuelto.png"
  },
  {
    city_mpg: 15,
    class: "coupe",
    combination_mpg: 17,
    cylinders: 8,
    displacement: 3.9,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 21,
    make: "Ferrari",
    model: "F8 Tributo",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/zqntDrX/ferrari-f8-tributo.png"
  },
  {
    city_mpg: 16,
    class: "convertible",
    combination_mpg: 18,
    cylinders: 8,
    displacement: 3.9,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 22,
    make: "Ferrari",
    model: "F8 Spider",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/0VcsKbKx/ferrari-f8-spider.png"
  },
  {
    city_mpg: 11,
    class: "coupe",
    combination_mpg: 13,
    cylinders: 12,
    displacement: 6.3,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 16,
    make: "Ferrari",
    model: "812 Superfast",
    transmission: "a",
    year: 2021,
    image: "https://i.ibb.co/Kvw0fHB/ferrari-812-superfast.png"
  },
  {
    city_mpg: 17,
    class: "coupe",
    combination_mpg: 19,
    cylinders: 6,
    displacement: 3.0,
    drive: "rwd",
    fuel_type: "hybrid",
    highway_mpg: 22,
    make: "Ferrari",
    model: "296 GTB",
    transmission: "a",
    year: 2023,
    image: "https://i.ibb.co/tp5Kn2Nv/Ferrari-296-GTB.png"
  },
  {
    city_mpg: 15,
    class: "coupe",
    combination_mpg: 18,
    cylinders: 8,
    displacement: 4.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 21,
    make: "McLaren",
    model: "720S",
    transmission: "a",
    year: 2021,
    image: "https://i.ibb.co/QFdsg75s/Mc-Laren-720-S.png"
  },
  {
    city_mpg: 18,
    class: "convertible",
    combination_mpg: 20,
    cylinders: 6,
    displacement: 3.0,
    drive: "rwd",
    fuel_type: "hybrid",
    highway_mpg: 23,
    make: "McLaren",
    model: "Artura",
    transmission: "a",
    year: 2024,
    image: "https://i.ibb.co/1YVBqd1x/mclaren-artura.png"
  },
  {
    city_mpg: 11,
    class: "coupe",
    combination_mpg: 13,
    cylinders: 12,
    displacement: 6.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 16,
    make: "Lamborghini",
    model: "Centenario",
    transmission: "a",
    year: 2020,
    image: "https://i.ibb.co/GQdfMLjb/lamborghini-centenario.png"
  },
   //----------------------------------------------------------------------------
   {
    city_mpg: 18,
    class: "coupe",
    combination_mpg: 20,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 24,
    make: "Porsche",
    model: "911 Carrera 4",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/cS9hdX69/porsche-911-carrera-4.png"
  },
  {
    city_mpg: 17,
    class: "coupe",
    combination_mpg: 19,
    cylinders: 6,
    displacement: 3.8,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 23,
    make: "Porsche",
    model: "911 Turbo S",
    transmission: "a",
    year: 2023,
    image: "https://i.ibb.co/Q3NTNwqh/Porsche-911-turbo-s.png"
  },
  {
    city_mpg: 20,
    class: "sedan",
    combination_mpg: 22,
    cylinders: 6,
    displacement: 2.9,
    drive: "awd",
    fuel_type: "hybrid",
    highway_mpg: 26,
    make: "Porsche",
    model: "Panamera 4 E-Hybrid",
    transmission: "a",
    year: 2023,
    image: "https://i.ibb.co/BVq8v0tp/Porsche-Panamera-4-E-Hybrid.png"
  },
  {
    city_mpg: 24,
    class: "suv",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 2.4,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 29,
    make: "Mitsubishi",
    model: "Outlander",
    transmission: "a",
    year: 2022,
    image: "https://i.ibb.co/PvJDXLQs/mitsubishi-outlander.png"
  },
  {
    city_mpg: 23,
    class: "suv",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 1.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Mitsubishi",
    model: "Eclipse Cross",
    transmission: "a",
    year: 2021,
    image: "https://i.ibb.co/FqLHPbcg/mitsubishi-eclipse-cross.png"
  },
  {
    city_mpg: 20,
    class: "sedan",
    combination_mpg: 22,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 27,
    make: "Mitsubishi",
    model: "Lancer",
    transmission: "a",
    year: 2017,
    image: "https://i.ibb.co/27ynHFHB/mitsubishi-lancer-evo.png"
  }
];















